language: python
env:
  global:
    - PATH=$PATH:/tmp/bin
  matrix:
    - BROWSER=firefox
    - REMOTE_ARG='--remote-url http://127.0.0.1:8080/#/' BROWSER=firefox

python:
  - "2.7"
services:
  - docker
install:
  # Install the Selenium Server
  - 'if [ -n "$REMOTE_ARG" ]; then wget http://selenium.googlecode.com/files/selenium-server-standalone-2.26.0.jar -O selenium-server.jar; fi'
  # Firefox is already installed
before_script:
    # install test dependencies
  - pip install -r requirements.txt
  # Setup headless X per http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'if [ -n "$REMOTE_ARG" ]; then (java -jar selenium-server.jar > /dev/null &); fi'
  - 'if [ -n "$REMOTE_ARG" ]; then sleep 60; fi'
script:
  - "python create_delete_cloud_Admin.py"
