language: python
os:
- linux
env:
  global:
  - PATH=$PATH:/tmp/bin
  - secure: gumYxNJsuviqOymMAWvwJ1Yd4llFS9UwHHRnxAReAw7oPpKlzXLO+KCdQdgiZW6ZYuYbx0JZe58QHVLJyLXypItrIJlQUGJs1zIM+RbuQ6RAADPiIaRM3yK721hdnEA23ve/qip4O0HaoKYI96osH4WfpM9v4mJdrUvvf5JaAJqQd9Rf/BT7tZbP/At6i7rlIz3B9Gp6cUmbg4WXB7tayPUEDOsUrZZoMHm14HfzVk8Eu8Qhtie4XMW56bcmyEf6gLpxnY6yYBeKUblBLp+qj+KfCYysAKEIPMw+fVoVtMOf6ZfGRiEC7eqgfJKEW1yo24/L0X4rSaahWTbof26myyp7UL0sDsVYE2vFjhZ8M0vLU2TT0Utq9eUq0ej1zKyKu/dFtndBd3rsCSJbAYxlDeof8lnR+rObpNeRlefJ2JWMYJQOzvpTvzJZjJbT8lXz6rOMvBjkd4a1akJCJ9AlX+kScH+a9qF+lgzmWrdQKEualGYQzQXUiXhXfMltf1jbjx69M7B/0mftduQS65zWtR0JkIvUcPA/clTR0WW4DVnuRv+16HQoa3u4Wb/PVAhGGJX1HpQEXKLvVzZUZs2nCc7GY9ZiiookadOo0K6I+Y0UrpZ/FEO64kuSKap5LrvL/C01rOZ0MHJbAWynm3edAjX2pErzJkEd2kg4nx5Xyrs=
  - secure: uBFVbCSoMyorrL7MiaawCWSkiwrWXvWRISNZHCkpeHdKo9d7WxwLZ9KVJoFTEr53PnX9Px28V922YqzEzksdWgL/eK0vSN0HAf7dZBIrKhhRW0X3Rc/Aj9h5t9dcXPJk+1UVRMJpiFj7JFtdvl5i67HfB6N1RlSMe7rv47lNGKFMvmBZIBsFqI8cFiHTIIkVoYVBa90mgQ30I6UH6I59jeZ0HcCMc7l593+HPkfZAETc0U+PWyQD6oLSOZQGTaZJImJYsuAlVR80+Sl77zHuWSVR+fjybdsMz+2DSl8e5dZ0iPMciPPZvr0ZxAYI+zqE1CHvv63a9Qp161GFLa8wnMYWkBGrITdXZeShuxQ8W0H7vAbGNgAUZlZ/sDjT7UUHwjng8M3h/EU8+PaHnQHBDGFCwBLrgl1sQMJP49e/sKOcBrXZdstwOTCFH1UQ/O0UYaylHEqOPOT1hFvy8AcFG0tGx/thvJpIhgYWYuVayKdUqbbtqj69Ql56CC8wIKy9a032BTFPLWFLEtHsGXW9f7Oj+ktmRMJFPJimCQSJvg5TWv4ktBk3I3XBk0xIgddNWdhjdrKXzibCELlShf+PzqhPt9qihs1ws9Zgl1MPRFYtTmE9fuwOZU/L1DZZR0ec6m9uztivBc6o9YIwojAtUIofW0qcD+QQeyPvmZx+aa8=
  - secure: W5vbS87sPIiIk5oQkry8bWklcA0Lb5wS2ZGB0p6TGLbINcXwWKQ0HC7UgJny/74sovGuT3gIKfaAGYhf1P2kbZmN1kBE5ItlAcp55jfRbck7sgZKQ6spc3wa32iR/2Na3WxOumeAYv6mIFbB+PE1htcYvTjUMhGLWCJExSawUafzJBZLkqf3YKNfK63DOhqaf8bqiTNbybCWBnJ/JkI43xoClceEE3au+0+xvLgX0T5sY2ZodTCghkgs23GO5RMjHZvtQOTLNW1xz9qmQ6c8d3Cw1Fsa64ijBXJURFWBhs0TM2AfBJ6uj6vvcwq3rzXfcIbr3L9UpQ6ZjWUUfveu0toUhRpsRXFtCjQcziFYdkT++QhrFxJgI8dFNF8NXoBvLFYAl6S3NGEICAPO6/+CxZbdkdPIvhqExzXw9LToH5HrqBZQ8WIl+Xs7bKkw9GlSPpwC928CflSS+h6J8uGq5/4hFKu4gaW546jbwe3gRo+8diQ9R80P6cBsl1+Qda2e+U8+AMPf0i9vAS80qAvI8zvZLuFBjCk306KIjVSPgqtSz5fqvnFm/RLjDth62ypNPbQqoVgcxYydHQQo2ov4CsF07Si7N0i76soGKOwuPPCGR83u+Tpy8WJF8R5mjArnOiJYO8LDqcauBmgQwHlmy+gKVTBYPFP75vsUL6eLSOY=
  matrix:
  - BROWSER=firefox
python:
- '2.7'
services:
- docker
before install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
install:
- if [ -n "$REMOTE_ARG" ]; then wget http://selenium.googlecode.com/files/selenium-server-standalone-2.26.0.jar
  -O selenium-server.jar; fi
- wget https://github.com/brianjjohnson/Regression-Tests/archive/master.zip
- tar -xvf master.zip
- docker-compose up -d
before_script:
- pip install -r requirements.txt
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [ -n "$REMOTE_ARG" ]; then (java -jar selenium-server.jar > /dev/null &); fi
- if [ -n "$REMOTE_ARG" ]; then sleep 60; fi
script:
- python create_delete_cloud_Admin.py
